backend:
  name: github
  repo: ladivergentedigital/web
  branch: main
  auth_endpoint: https://api.netlify.com/auth?provider=github&site_id=7abb3c9b-b875-4d83-861f-034f44b13b7e


media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "site"
    label: "Sitio"
    files:
      - file: "src/content/site/home.json"
        label: "Home"
        name: "home"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Bajada", name: "subtitle", widget: "text" }

      - file: "src/content/site/legal.json"
        label: "Legales"
        name: "legal"
        fields:
          - { label: "Términos y condiciones", name: "terms", widget: "markdown" }
          - { label: "Política de privacidad", name: "privacy", widget: "markdown" }

  - name: "ebooks"
    label: "eBooks"
    folder: "src/content/ebooks"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Autor/a", name: "author", widget: "string" }
      - { label: "Páginas", name: "pages", widget: "number" }
      - { label: "Precio (ARS)", name: "price", widget: "number" }
      - { label: "Formato", name: "format", widget: "select", options: ["PDF", "EPUB"] }
      - { label: "Portada", name: "cover", widget: "image" }
      - { label: "Descripción", name: "description", widget: "markdown" }

  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Contenido", name: "body", widget: "markdown" }

  - name: "revista"
    label: "Revista"
    folder: "src/content/revista"
    create: true
    fields:
      - { label: "Mes", name: "month", widget: "string", hint: "Ej: 2026-01" }
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descripción", name: "description", widget: "markdown" }
      - { label: "PDF (opcional)", name: "pdf", widget: "file", required: false }
